name: zen-browser
base: core24 # the base snap is the execution environment for this snap
version: '1.0.0-a.35' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  zen-browser:
    source: https://github.com/zen-browser/desktop/releases/download/${CRAFT_PROJECT_VERSION}/zen.linux-specific.tar.bz2
    plugin: dump
    build-attributes:
    - enable-patchelf
