name: zen-browser
base: core24 # the base snap is the execution environment for this snap
version: '1.0.0-a.35' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots
compression: lzo

apps:
  zen-browser:
    command: zen
    extensions: [gnome]
    environment:
      GTK_USE_PORTAL: 1
      HOME: "$SNAP_USER_COMMON"
    slots:
      - dbus-daemon
      - mpris
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - avahi-observe
      - browser-sandbox
      - camera
      - cups-control
      - gsettings
      - hardware-observe
      - home
      - joystick
      - login-session-observe
      - network
      - network-observe
      - opengl
      - removable-media
      - screen-inhibit-control
      - system-packages-doc
      - u2f-devices
      - unity7
      - upower-observe

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

  dot-zen:
    interface: personal-files
    read: [$HOME/.zen]

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: org.mozilla.firefox

layout:
  /usr/share/libdrm:
    bind: $SNAP/gnome-platform/usr/share/libdrm
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  zen-browser:
    source: https://github.com/zen-browser/desktop/releases/download/${CRAFT_PROJECT_VERSION}/zen.linux-specific.tar.bz2
    plugin: dump
    build-attributes:
    - enable-patchelf
    stage-packages:
      - libasound2
      - libcurl4
      - libpci3
      - libpipewire-0.3-0
      - libpipewire-0.3-modules
      - libspa-0.2-modules
      - libspeechd2
      - libvulkan1
      - libxt6
      - mesa-vulkan-drivers
      - pipewire-bin
      - pipewire-pulse
