name: zen-browser
base: core24
version: '1.0.0-a.37'
summary: Zen is the best way to browse the web.
description: |
  This is an unofficial snap package of Zen browser

  Zen - Your Browser, your way

  Experience tranquility while browsing the internet
  with Zen! Our mission is to give you a perfect
  balance for speed, privacy and productivity

  Zen thrives on the contributions of its vibrant community.
  As an open-source project, Zen encourages collaboration
  and innovation, allowing users and developers alike to
  shape the future of the browser.


grade: stable
confinement: strict
compression: lzo

apps:
  zen-browser:
    command-chain:
      - bin/gpu-2404-wrapper
    command: zen
    extensions: [gnome]
    environment:
      GTK_USE_PORTAL: 1
      HOME: "$SNAP_USER_DATA"
    slots:
      - dbus-daemon
      - mpris
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - avahi-observe
      - browser-sandbox
      - dot-gtk3
      - dot-zen
      - camera
      - cups-control
      - gsettings
      - hardware-observe
      - home
      - joystick
      - login-session-observe
      - network
      - network-observe
      - opengl
      - removable-media
      - screen-inhibit-control
      - system-packages-doc
      - u2f-devices
      - unity7
      - upower-observe

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

  dot-gtk3:
    interface: personal-files
    read: [$HOME/.config/gtk-3.0]

  dot-zen:
    interface: personal-files
    write: [$HOME/.zen]

  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: org.mozilla.firefox

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d

parts:
  zen-browser:
    source: https://github.com/zen-browser/desktop/releases/download/$CRAFT_PROJECT_VERSION/zen.linux-specific.tar.bz2
    plugin: dump
    build-attributes:
    - enable-patchelf
    stage-packages:
      - libfontconfig1
      - libpangoft2-1.0-0
      - libpci3
      - libxfixes3
      - libxrender1
    override-build: |
      craftctl default
      DESKTOP_DIRECTORY_PATH="${CRAFT_PART_INSTALL}/snap/gui"
      ICON_PATH="${DESKTOP_DIRECTORY_PATH}/zen-browser.png"

      mkdir -p "${DESKTOP_DIRECTORY_PATH}"
      cp ${CRAFT_PART_SRC}/browser/chrome/icons/default/default48.png "${ICON_PATH}"
      echo "Exec=zen-browser" > "${DESKTOP_DIRECTORY_PATH}/zen-browser.desktop"
      echo "Icon=${SNAP}/meta/gui/zen-browser.png" >> "${DESKTOP_DIRECTORY_PATH}/zen-browser.desktop"



  gpu-2404:
    after: [zen-browser]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
    - bin/gpu-2404-wrapper
