name: zen-browser
base: core24
version: '1.0.0-a.37'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable
confinement: devmode # use 'strict' once you have the right plugs and slots
compression: lzo

apps:
  zen-browser:
    command-chain:
      - bin/gpu-2404-wrapper
    command: zen
    extensions: [gnome]
    environment:
      GTK_USE_PORTAL: 1
      HOME: "$SNAP_USER_COMMON"
    slots:
      - dbus-daemon
      - mpris
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - avahi-observe
      - browser-sandbox
      - camera
      - cups-control
      - gsettings
      - hardware-observe
      - home
      - joystick
      - login-session-observe
      - network
      - network-observe
      - opengl
      - removable-media
      - screen-inhibit-control
      - system-packages-doc
      - u2f-devices
      - unity7
      - upower-observe

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

  dot-zen:
    interface: personal-files
    read: [$HOME/.zen]

  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: org.mozilla.firefox

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d

parts:
  zen-browser:
    source: https://github.com/zen-browser/desktop/releases/download/$CRAFT_PROJECT_VERSION/zen.linux-specific.tar.bz2
    plugin: dump
    build-attributes:
    - enable-patchelf
    stage-packages:
      - libfontconfig1
      - libpangoft2-1.0-0
      - libxfixes3
      - libxrender1
  gpu-2404:
    after: [zen-browser]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
    - bin/gpu-2404-wrapper
